apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdicidr-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdicidr
  template:
    metadata:
      labels:
        app: rdicidr
    spec:
      containers:
      - name: rdicidr-app
        image: ubaidawan/rdicidr:latest
        ports:
        - containerPort: 80
        env:
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: rdicidr-secret
              key: my-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"